=== c3b2a7/desensitize/desensitize-core/src/main/resources/desensitize.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.smyfinancial.com/schema/desensitize"
            xmlns="http://www.smyfinancial.com/schema/desensitize">

    <xsd:element name="config">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <xsd:element ref="table"/>
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="table">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <xsd:element ref="column"/>
                </xsd:choice>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[唯一的表名]]></xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="selectFromEncryptedTable" type="xsd:boolean" default="false">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[是否走加密表查询]]></xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="tableNameCaseInsensitive" type="xsd:boolean" default="true">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[表名是否大小写不敏感]]></xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="column">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[唯一的列名]]></xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="original" type="xsd:boolean" default="false">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[是否属于原始表的配置]]></xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="minimumMatch" type="xsd:integer">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[最小匹配长度]]></xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="regex" type="xsd:boolean" default="false">
                <xsd:annotation>
                    <xsd:documentation><![CDATA[是否为正则表达式]]></xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== c3b2a7/desensitize/desensitize-core/src/test/resources/desensitize-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://lolico.me/schema/desensitize"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://lolico.me/schema/desensitize desensitize.xsd">
    <table name="table1">
        <column name="column1" original="true" minimumMatch="1"/> <!--原始表写加密值，字段存在like查询场景，最小匹配长度1-->
        <column name="column2" original="true"/> <!--原始表写加密值-->
    </table>
    <table name="table2" selectFromEncryptedTable="true">
        <column name="column3" original="true"/> <!--原始表写加密值，加密表同样写加密值-->
        <column name="column4" original="true"/> <!--原始表写加密值，加密表同样写加密值-->
        <column name="column5"/> <!--加密表写加密值-->
    </table>
    <table name="table3" selectFromEncryptedTable="true">
        <column name="column6"/> <!--加密表写加密值-->
        <column name="column7"/> <!--加密表写加密值-->
    </table>
</config>
